// Package zdeflate is a pure Go port of the zlib 1.3.1 compression algorithm
// (deflate.c + trees.c).
//
// The goal is compressed output that is **byte-for-byte identical** to C zlib
// under the same parameters (windowBits=15 / memLevel=8 / Z_DEFAULT_STRATEGY,
// level 0-9). Therefore every algorithmic decision — the hash function, lazy
// matching, chain truncation, tie-breaks when building the Huffman trees, bit
// emission order, block type (stored/static/dynamic) decisions — is ported
// exactly from the zlib source. A few hot spots deviate mechanically for
// speed (wide loads and masked probe loads in longestMatch, SWAR in
// slideHash, independently computed hashes in the batch-insert loops, a
// 64-bit bit accumulator and a register-local compressBlock here in
// trees.go); each carries a comment proving the deviation cannot change any
// output byte, and all are covered by the byte-for-byte cross-check
// matrices.
//
// This file corresponds to zlib's trees.c.
package zdeflate

import "encoding/binary"

const (
	lengthCodes = 29                         // number of length codes (not counting END_BLOCK)
	literals    = 256                        // literals 0..255
	lCodes      = literals + 1 + lengthCodes // 286
	dCodes      = 30                         // number of distance codes
	blCodes     = 19                         // number of codes used to transfer the bit lengths
	heapSize    = 2*lCodes + 1               // 573
	maxBits     = 15                         // maximum code length
	maxBlBits   = 7                          // maximum code length for the bit length tree

	endBlock   = 256 // end-of-block symbol
	rep3_6     = 16  // repeat previous bit length 3-6 times
	repz3_10   = 17  // repeat a zero bit length 3-10 times
	repz11_138 = 18  // repeat a zero bit length 11-138 times

	storedBlockType = 0
	staticTreesType = 1
	dynTreesType    = 2

	distCodeLen = 512
)

// ctData corresponds to C's ct_data: fc is the Freq/Code union, dl the Dad/Len union.
// The uint16 (ush) width and wraparound semantics must be preserved.
type ctData struct {
	fc uint16 // Freq / Code
	dl uint16 // Dad / Len
}

var extraLbits = [lengthCodes]int{0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0}

var extraDbits = [dCodes]int{0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13}

var extraBlbits = [blCodes]int{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 7}

var blOrder = [blCodes]uint8{16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15}

// Static tables, generated by initStaticTrees using the algorithm of tr_static_init
var (
	staticLtree [lCodes + 2]ctData
	staticDtree [dCodes]ctData
	distCode    [distCodeLen]uint8
	lengthCode  [maxMatch - minMatch + 1]uint8
	baseLength  [lengthCodes]int
	baseDist    [dCodes]int
)

type staticTreeDesc struct {
	staticTree []ctData // static tree, nil for the bl tree
	extraBits  []int
	extraBase  int
	elems      int
	maxLength  int
}

var (
	staticLDesc  staticTreeDesc
	staticDDesc  staticTreeDesc
	staticBLDesc staticTreeDesc
)

type treeDesc struct {
	dynTree  []ctData
	maxCode  int
	statDesc *staticTreeDesc
}

func init() {
	// Map length (0..255) to length code (0..28)
	length := 0
	for code := 0; code < lengthCodes-1; code++ {
		baseLength[code] = length
		for n := 0; n < 1<<extraLbits[code]; n++ {
			lengthCode[length] = uint8(code)
			length++
		}
	}
	// Length 255 (match length 258) is represented by code 285
	lengthCode[length-1] = lengthCodes - 1

	// Map distance (0..32K) to distance code (0..29)
	dist := 0
	for code := 0; code < 16; code++ {
		baseDist[code] = dist
		for n := 0; n < 1<<extraDbits[code]; n++ {
			distCode[dist] = uint8(code)
			dist++
		}
	}
	dist >>= 7 // from now on, all distances are divided by 128
	for code := 16; code < dCodes; code++ {
		baseDist[code] = dist << 7
		for n := 0; n < 1<<(extraDbits[code]-7); n++ {
			distCode[256+dist] = uint8(code)
			dist++
		}
	}

	// Construct the static literal tree
	var blCount [maxBits + 1]uint16
	n := 0
	for n <= 143 {
		staticLtree[n].dl = 8
		blCount[8]++
		n++
	}
	for n <= 255 {
		staticLtree[n].dl = 9
		blCount[9]++
		n++
	}
	for n <= 279 {
		staticLtree[n].dl = 7
		blCount[7]++
		n++
	}
	for n <= 287 {
		staticLtree[n].dl = 8
		blCount[8]++
		n++
	}
	genCodes(staticLtree[:], lCodes+1, &blCount)

	// Static distance tree: all codes are 5 bits
	for i := 0; i < dCodes; i++ {
		staticDtree[i].dl = 5
		staticDtree[i].fc = uint16(biReverse(uint32(i), 5))
	}

	staticLDesc = staticTreeDesc{staticLtree[:], extraLbits[:], literals + 1, lCodes, maxBits}
	staticDDesc = staticTreeDesc{staticDtree[:], extraDbits[:], 0, dCodes, maxBits}
	staticBLDesc = staticTreeDesc{nil, extraBlbits[:], 0, blCodes, maxBlBits}
}

// dCode corresponds to the d_code(dist) macro; dist is distance-1
func dCode(dist int) int {
	if dist < 256 {
		return int(distCode[dist])
	}
	return int(distCode[256+(dist>>7)])
}

// biReverse reverses the low len bits of code
func biReverse(code uint32, length int) uint32 {
	var res uint32
	for {
		res |= code & 1
		code >>= 1
		res <<= 1
		length--
		if length <= 0 {
			break
		}
	}
	return res >> 1
}

/* ------------------------------------------------------------------ */
/* Bit stream output (and the pending buffer)                          */
/* ------------------------------------------------------------------ */

func (s *state) putByte(b byte) {
	s.pendingBuf[s.pending] = b
	s.pending++
}

// putShort outputs 16 bits, LSB first
func (s *state) putShort(w uint16) {
	s.putByte(byte(w))
	s.putByte(byte(w >> 8))
}

// sendBits corresponds to the send_bits macro, with C's 16-bit bi_buf widened
// to a 64-bit accumulator: bits are still emitted least-significant first in
// the same order, so the byte stream is unchanged; only the point at which
// full bytes move to the pending buffer differs (never later than C would
// have observed them via flush_pending, which always drains through biFlush
// or biWindup below). length <= 15 and biValid < 48 on entry, so the shifted
// value always fits.
func (s *state) sendBits(value, length int) {
	s.biBuf |= uint64(value) << uint(s.biValid)
	s.biValid += length
	if s.biValid >= 48 {
		b := s.pendingBuf[s.pending : s.pending+6]
		binary.LittleEndian.PutUint32(b, uint32(s.biBuf))
		binary.LittleEndian.PutUint16(b[4:], uint16(s.biBuf>>32))
		s.pending += 6
		s.biBuf >>= 48
		s.biValid -= 48
	}
}

func (s *state) sendCode(c int, tree []ctData) {
	s.sendBits(int(tree[c].fc), int(tree[c].dl))
}

// biFlush flushes the bit buffer down to a byte residue, keeping at most 7
// bits (the same residue C's bi_flush leaves: the total bit count mod 8)
func (s *state) biFlush() {
	for s.biValid >= 8 {
		s.putByte(byte(s.biBuf))
		s.biBuf >>= 8
		s.biValid -= 8
	}
}

// biWindup flushes the bit buffer and aligns to a byte boundary
func (s *state) biWindup() {
	for s.biValid > 0 {
		s.putByte(byte(s.biBuf))
		s.biBuf >>= 8
		s.biValid -= 8
	}
	s.biBuf = 0
	s.biValid = 0
}

/* ------------------------------------------------------------------ */
/* Tree construction                                                    */
/* ------------------------------------------------------------------ */

// initBlock initializes a new block
func (s *state) initBlock() {
	for n := 0; n < lCodes; n++ {
		s.dynLtree[n].fc = 0
	}
	for n := 0; n < dCodes; n++ {
		s.dynDtree[n].fc = 0
	}
	for n := 0; n < blCodes; n++ {
		s.blTree[n].fc = 0
	}
	s.dynLtree[endBlock].fc = 1
	s.optLen = 0
	s.staticLen = 0
	s.symNext = 0
	s.matches = 0
}

// trInit corresponds to _tr_init
func (s *state) trInit() {
	s.lDesc = treeDesc{s.dynLtree[:], 0, &staticLDesc}
	s.dDesc = treeDesc{s.dynDtree[:], 0, &staticDDesc}
	s.blDesc = treeDesc{s.blTree[:], 0, &staticBLDesc}
	s.biBuf = 0
	s.biValid = 0
	s.initBlock()
}

const smallest = 1

// smaller corresponds to the smaller macro: equal frequencies tie-break by depth
func smaller(tree []ctData, n, m int, depth []uint8) bool {
	return tree[n].fc < tree[m].fc ||
		(tree[n].fc == tree[m].fc && depth[n] <= depth[m])
}

// pqdownheap restores the heap property
func (s *state) pqdownheap(tree []ctData, k int) {
	v := s.heap[k]
	j := k << 1 // left son of k
	for j <= s.heapLen {
		// j points to the smaller of the two sons
		if j < s.heapLen && smaller(tree, s.heap[j+1], s.heap[j], s.depth[:]) {
			j++
		}
		if smaller(tree, v, s.heap[j], s.depth[:]) {
			break
		}
		s.heap[k] = s.heap[j]
		k = j
		j <<= 1
	}
	s.heap[k] = v
}

// genBitlen computes the optimal bit lengths and updates opt_len/static_len
func (s *state) genBitlen(desc *treeDesc) {
	tree := desc.dynTree
	maxCode := desc.maxCode
	stree := desc.statDesc.staticTree
	extra := desc.statDesc.extraBits
	base := desc.statDesc.extraBase
	maxLength := desc.statDesc.maxLength
	overflow := 0

	for bits := 0; bits <= maxBits; bits++ {
		s.blCount[bits] = 0
	}

	// First pass: compute the optimal bit lengths (the bit length tree may overflow)
	tree[s.heap[s.heapMax]].dl = 0 // root of the tree

	for h := s.heapMax + 1; h < heapSize; h++ {
		n := s.heap[h]
		bits := int(tree[tree[n].dl].dl) + 1 // tree[n].dl is still Dad here
		if bits > maxLength {
			bits = maxLength
			overflow++
		}
		tree[n].dl = uint16(bits) // overwrite Dad with Len

		if n > maxCode {
			continue // not a leaf node
		}

		s.blCount[bits]++
		xbits := 0
		if n >= base {
			xbits = extra[n-base]
		}
		f := uint64(tree[n].fc)
		s.optLen += f * uint64(bits+xbits)
		if stree != nil {
			s.staticLen += f * uint64(int(stree[n].dl)+xbits)
		}
	}
	if overflow == 0 {
		return
	}

	// Handle code length overflow (triggered by obj2/pic in the Calgary corpus)
	for {
		bits := maxLength - 1
		for s.blCount[bits] == 0 {
			bits--
		}
		s.blCount[bits]--
		s.blCount[bits+1] += 2
		s.blCount[maxLength]--
		overflow -= 2
		if overflow <= 0 {
			break
		}
	}

	// Recompute all bit lengths, scanning in increasing frequency order
	h := heapSize
	for bits := maxLength; bits != 0; bits-- {
		n := int(s.blCount[bits])
		for n != 0 {
			h--
			m := s.heap[h]
			if m > maxCode {
				continue
			}
			if int(tree[m].dl) != bits {
				s.optLen += (uint64(bits) - uint64(tree[m].dl)) * uint64(tree[m].fc)
				tree[m].dl = uint16(bits)
			}
			n--
		}
	}
}

// genCodes generates canonical Huffman codes from the bit lengths (bit-reversed)
func genCodes(tree []ctData, maxCode int, blCount *[maxBits + 1]uint16) {
	var nextCode [maxBits + 1]uint16
	var code uint32

	for bits := 1; bits <= maxBits; bits++ {
		code = (code + uint32(blCount[bits-1])) << 1
		nextCode[bits] = uint16(code)
	}

	for n := 0; n <= maxCode; n++ {
		length := int(tree[n].dl)
		if length == 0 {
			continue
		}
		tree[n].fc = uint16(biReverse(uint32(nextCode[length]), length))
		nextCode[length]++
	}
}

// buildTree constructs a Huffman tree and generates the codes
func (s *state) buildTree(desc *treeDesc) {
	tree := desc.dynTree
	stree := desc.statDesc.staticTree
	elems := desc.statDesc.elems
	maxCode := -1

	// Construct the initial heap
	s.heapLen = 0
	s.heapMax = heapSize

	for n := 0; n < elems; n++ {
		if tree[n].fc != 0 {
			s.heapLen++
			s.heap[s.heapLen] = n
			maxCode = n
			s.depth[n] = 0
		} else {
			tree[n].dl = 0
		}
	}

	// The pkzip format requires at least one distance code; force at least two codes of non-zero frequency
	for s.heapLen < 2 {
		var node int
		if maxCode < 2 {
			maxCode++
			node = maxCode
		} else {
			node = 0
		}
		s.heapLen++
		s.heap[s.heapLen] = node
		tree[node].fc = 1
		s.depth[node] = 0
		s.optLen-- // matches C: unsigned wraparound
		if stree != nil {
			s.staticLen -= uint64(stree[node].dl)
		}
	}
	desc.maxCode = maxCode

	// Establish sub-heaps
	for n := s.heapLen / 2; n >= 1; n-- {
		s.pqdownheap(tree, n)
	}

	// Repeatedly merge the two nodes of least frequency
	node := elems // next internal node
	for {
		n := s.heap[smallest] // pqremove
		s.heap[smallest] = s.heap[s.heapLen]
		s.heapLen--
		s.pqdownheap(tree, smallest)

		m := s.heap[smallest] // node of next least frequency

		s.heapMax--
		s.heap[s.heapMax] = n // keep sorted by frequency
		s.heapMax--
		s.heap[s.heapMax] = m

		// Create the parent node
		tree[node].fc = tree[n].fc + tree[m].fc
		d := s.depth[n]
		if s.depth[m] > d {
			d = s.depth[m]
		}
		s.depth[node] = d + 1
		tree[n].dl = uint16(node) // Dad
		tree[m].dl = uint16(node)

		s.heap[smallest] = node
		node++
		s.pqdownheap(tree, smallest)

		if s.heapLen < 2 {
			break
		}
	}

	s.heapMax--
	s.heap[s.heapMax] = s.heap[smallest]

	s.genBitlen(desc)
	genCodes(tree, maxCode, &s.blCount)
}

// scanTree scans the tree to accumulate frequencies for the bit length tree
func (s *state) scanTree(tree []ctData, maxCode int) {
	prevlen := -1
	nextlen := int(tree[0].dl)
	count := 0
	maxCount := 7
	minCount := 4

	if nextlen == 0 {
		maxCount = 138
		minCount = 3
	}
	tree[maxCode+1].dl = 0xffff // guard

	for n := 0; n <= maxCode; n++ {
		curlen := nextlen
		nextlen = int(tree[n+1].dl)
		count++
		if count < maxCount && curlen == nextlen {
			continue
		} else if count < minCount {
			s.blTree[curlen].fc += uint16(count)
		} else if curlen != 0 {
			if curlen != prevlen {
				s.blTree[curlen].fc++
			}
			s.blTree[rep3_6].fc++
		} else if count <= 10 {
			s.blTree[repz3_10].fc++
		} else {
			s.blTree[repz11_138].fc++
		}
		count = 0
		prevlen = curlen
		if nextlen == 0 {
			maxCount = 138
			minCount = 3
		} else if curlen == nextlen {
			maxCount = 6
			minCount = 3
		} else {
			maxCount = 7
			minCount = 4
		}
	}
}

// sendTree sends a tree using the codes of the bit length tree
func (s *state) sendTree(tree []ctData, maxCode int) {
	prevlen := -1
	nextlen := int(tree[0].dl)
	count := 0
	maxCount := 7
	minCount := 4

	if nextlen == 0 {
		maxCount = 138
		minCount = 3
	}

	for n := 0; n <= maxCode; n++ {
		curlen := nextlen
		nextlen = int(tree[n+1].dl)
		count++
		if count < maxCount && curlen == nextlen {
			continue
		} else if count < minCount {
			for {
				s.sendCode(curlen, s.blTree[:])
				count--
				if count == 0 {
					break
				}
			}
		} else if curlen != 0 {
			if curlen != prevlen {
				s.sendCode(curlen, s.blTree[:])
				count--
			}
			s.sendCode(rep3_6, s.blTree[:])
			s.sendBits(count-3, 2)
		} else if count <= 10 {
			s.sendCode(repz3_10, s.blTree[:])
			s.sendBits(count-3, 3)
		} else {
			s.sendCode(repz11_138, s.blTree[:])
			s.sendBits(count-11, 7)
		}
		count = 0
		prevlen = curlen
		if nextlen == 0 {
			maxCount = 138
			minCount = 3
		} else if curlen == nextlen {
			maxCount = 6
			minCount = 3
		} else {
			maxCount = 7
			minCount = 4
		}
	}
}

// buildBlTree constructs the bit length tree; returns the index of the last non-zero code length in bl_order
func (s *state) buildBlTree() int {
	s.scanTree(s.dynLtree[:], s.lDesc.maxCode)
	s.scanTree(s.dynDtree[:], s.dDesc.maxCode)

	s.buildTree(&s.blDesc)

	var maxBlindex int
	for maxBlindex = blCodes - 1; maxBlindex >= 3; maxBlindex-- {
		if s.blTree[blOrder[maxBlindex]].dl != 0 {
			break
		}
	}
	s.optLen += 3*(uint64(maxBlindex)+1) + 5 + 5 + 4
	return maxBlindex
}

// sendAllTrees sends the tree header of a dynamic block
func (s *state) sendAllTrees(lcodes, dcodes, blcodes int) {
	s.sendBits(lcodes-257, 5)
	s.sendBits(dcodes-1, 5)
	s.sendBits(blcodes-4, 4)
	for rank := 0; rank < blcodes; rank++ {
		s.sendBits(int(s.blTree[blOrder[rank]].dl), 3)
	}
	s.sendTree(s.dynLtree[:], lcodes-1)
	s.sendTree(s.dynDtree[:], dcodes-1)
}

// trAlign corresponds to _tr_align: send an empty static block for byte alignment (Z_PARTIAL_FLUSH)
func (s *state) trAlign() {
	s.sendBits(staticTreesType<<1, 3)
	s.sendCode(endBlock, staticLtree[:])
	s.biFlush()
}

// trStoredBlock sends a stored block; when buf is nil, only the block header is written (len=0)
func (s *state) trStoredBlock(buf []byte, last bool) {
	s.sendBits(storedBlockType<<1+b2i(last), 3)
	s.biWindup()
	storedLen := len(buf)
	s.putShort(uint16(storedLen))
	s.putShort(^uint16(storedLen))
	if storedLen > 0 {
		copy(s.pendingBuf[s.pending:], buf)
	}
	s.pending += storedLen
}

// compressBlock sends the block data using the given trees.
//
// It emits exactly the bit sequence of the C loop (same codes, same extra
// bits, same order), but accumulates into local copies of biBuf/biValid so
// the compiler keeps them in registers across the symbol loop. Whole bytes
// are moved to pendingBuf in 32-bit groups whenever 32 or more bits are
// buffered, checked once after each code+extra pair: a pair adds at most
// maxBits+13 == 28 bits, so biValid never exceeds 31+28 == 59 < 64 and no
// bit is ever lost. Only the flush points differ from sendBits — as with
// the 64-bit accumulator itself, pendingBuf receives the same bytes in the
// same order (whole bytes drained bottom-first), so the output is unchanged.
func (s *state) compressBlock(ltree, dtree []ctData) {
	buf, valid, pending := s.biBuf, s.biValid, s.pending
	if s.symNext != 0 {
		symLc := s.symLc[:s.symNext]
		symDist := s.symDist[:s.symNext]
		for sx, lcb := range symLc {
			dist := int(symDist[sx])
			lc := int(lcb)
			if dist == 0 {
				e := ltree[lc] // literal
				buf |= uint64(e.fc) << uint(valid)
				valid += int(e.dl)
			} else {
				// lc is match length - MIN_MATCH
				code := int(lengthCode[lc])
				e := ltree[code+literals+1]
				buf |= uint64(e.fc) << uint(valid)
				valid += int(e.dl)
				if extra := extraLbits[code]; extra != 0 {
					buf |= uint64(lc-baseLength[code]) << uint(valid)
					valid += extra
				}
				if valid >= 32 {
					binary.LittleEndian.PutUint32(s.pendingBuf[pending:], uint32(buf))
					pending += 4
					buf >>= 32
					valid -= 32
				}
				dist-- // dist becomes match distance - 1
				code = dCode(dist)
				e = dtree[code]
				buf |= uint64(e.fc) << uint(valid)
				valid += int(e.dl)
				if extra := extraDbits[code]; extra != 0 {
					buf |= uint64(dist-baseDist[code]) << uint(valid)
					valid += extra
				}
			}
			if valid >= 32 {
				binary.LittleEndian.PutUint32(s.pendingBuf[pending:], uint32(buf))
				pending += 4
				buf >>= 32
				valid -= 32
			}
		}
	}
	e := ltree[endBlock]
	buf |= uint64(e.fc) << uint(valid)
	valid += int(e.dl)
	s.biBuf, s.biValid, s.pending = buf, valid, pending
}

// trFlushBlock decides the best encoding for the block (dynamic/static/stored) and outputs it.
// buf is the slice of window for the current block (nil when block_start < 0), storedLen its length.
func (s *state) trFlushBlock(buf []byte, storedLen int, last bool) {
	var optLenb, staticLenb uint64
	maxBlindex := 0

	if s.level > 0 {
		// Construct the literal and distance trees
		s.buildTree(&s.lDesc)
		s.buildTree(&s.dDesc)
		// Construct the bit length tree
		maxBlindex = s.buildBlTree()

		// Compute the block lengths in bytes
		optLenb = (s.optLen + 3 + 7) >> 3
		staticLenb = (s.staticLen + 3 + 7) >> 3

		if staticLenb <= optLenb {
			optLenb = staticLenb
		}
	} else {
		optLenb = uint64(storedLen) + 5
		staticLenb = optLenb
	}

	if uint64(storedLen)+4 <= optLenb && buf != nil {
		// stored block (4: two 16-bit length fields)
		s.trStoredBlock(buf[:storedLen], last)
	} else if staticLenb == optLenb {
		s.sendBits(staticTreesType<<1+b2i(last), 3)
		s.compressBlock(staticLtree[:], staticDtree[:])
	} else {
		s.sendBits(dynTreesType<<1+b2i(last), 3)
		s.sendAllTrees(s.lDesc.maxCode+1, s.dDesc.maxCode+1, maxBlindex+1)
		s.compressBlock(s.dynLtree[:], s.dynDtree[:])
	}
	s.initBlock()

	if last {
		s.biWindup()
	}
}

// tallyLit corresponds to the _tr_tally_lit macro; returns whether the block must be flushed
func (s *state) tallyLit(c byte) bool {
	s.symDist[s.symNext] = 0
	s.symLc[s.symNext] = c
	s.symNext++
	s.dynLtree[c].fc++
	return s.symNext == symEnd
}

// tallyDist corresponds to the _tr_tally_dist macro
func (s *state) tallyDist(distance, length int) bool {
	s.symDist[s.symNext] = uint16(distance)
	s.symLc[s.symNext] = byte(length)
	s.symNext++
	dist := distance - 1
	s.dynLtree[int(lengthCode[length])+literals+1].fc++
	s.dynDtree[dCode(dist)].fc++
	return s.symNext == symEnd
}

func b2i(b bool) int {
	if b {
		return 1
	}
	return 0
}
